patient:
  name: Затейчук Владимир Евгеньевич
  age: 53
  sex: Мужской
  date_of_birth: 1971-02-23
  chronic_conditions:
    - Недостаточность кардии
    - Гастропатия эритематозная
  current_medications:
    - Омепразол 20 мг
    - Метоклопрамид 10 мг
  allergies:
    - Пенициллины (сыпь)
